name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/cancel.yml
      - .github/workflows/codeql.yml
      - .github/workflows/release.yml
      - .gitignore
      - gradle.properties
      - LICENSE
      - README.md
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: opengoodio/central-workflows/.github/workflows/gradle-lib-postgres-build.yml@main
    with:
      postgres-admin-db-uri: ${{ vars.POSTGRES_ADMIN_DB_URI }}
      postgres-build-db-uri: ${{ vars.POSTGRES_BUILD_DB_URI }}
      run-gradle-validation: true
    secrets:
      fossa-api-key: ${{ secrets.FOSSA_API_KEY }}
      postgres-admin-password: ${{ secrets.POSTGRES_ADMIN_DB_PASSWORD }}
      postgres-build-db-svc-name: ${{ secrets.POSTGRES_BUILD_DB_SVC_NAME }}
      postgres-build-db-svc-password: ${{ secrets.POSTGRES_BUILD_DB_SVC_PASSWORD }}
