name: gradle-plugin-build

on:
  workflow_call:
    inputs:
      java-distribution:
        type: string
        description: Name of Java JDK distribution to use
        required: false
        default: temurin
      java-version:
        type: number
        description: Version of Java JDK to use
        required: false
        default: 17
      run-gradle-validation:
        type: boolean
        description: Value indicating if Gradle validation step should run
        required: true
    secrets:
      fossa-api-key:
        description: FOSSA licensing scan API key
        required: true

jobs:
  gradle-plugin-build:
    name: Gradle Plugin Build
    runs-on: ubuntu-latest
    if: ${{ github.event.head_commit.message != 'Create release' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Validate Gradle Wrapper
        if: ${{ inputs.run-gradle-validation == true }}
        uses: gradle/wrapper-validation-action@v2.1.2

      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}

      - name: Build
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: clean build
          gradle-version: wrapper

      - name: Codestyle
        uses: fabiocapasso93/gha-kotlin-linter@v1.1

      - name: Coverage
        uses: codecov/codecov-action@v4.1.0
        with:
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
          verbose: true

      - name: FOSSA
        uses: fossas/fossa-action@v1.3.3
        with:
          api-key: ${{ secrets.fossa-api-key }}
