name: gradle-github-release

on:
  workflow_call:
    inputs:
      git-email:
        type: string
        description: Git user email address
        required: true
      git-user:
        type: string
        description: Git user username
        required: true
      java-distribution:
        type: string
        description: Name of Java JDK distribution to use
        required: false
        default: temurin
      java-version:
        type: number
        description: Version of Java JDK to use
        required: false
        default: 17
      run-gradle-validation:
        type: boolean
        description: Value indicating if Gradle validation step should run
        required: true

jobs:
  gradle-github-release:
    name: Gradle GitHub Release
    runs-on: ubuntu-latest
    if: ${{ github.event.head_commit.message == 'Create release' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Validate Gradle Wrapper
        if: ${{ inputs.run-gradle-validation == true }}
        uses: gradle/wrapper-validation-action@v2.0.0

      - name: Setup Git
        run: |
          git config user.email ${GIT_EMAIL}
          git config user.name ${GIT_USER}
        env:
          GIT_EMAIL: ${{ inputs.git-user }}
          GIT_USER: ${{ inputs.git-email }}

      - name: Setup Java
        uses: actions/setup-java@v4.0.0
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}

      - name: Release and Publish
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: clean release -PskipTests=true -Prelease.useAutomaticVersion=true
          gradle-version: wrapper
        env:
          GITHUB_USER: ${{ inputs.git-user }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
